Update flawfinder.yml
change flawfinder pipeline to work in a more basic way

diff --git a/.github/workflows/flawfinder.yml b/.github/workflows/flawfinder.yml
--- a/.github/workflows/flawfinder.yml
+++ b/.github/workflows/flawfinder.yml
@@ -1,38 +1,30 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
+name: Flawfinder
 
-name: flawfinder
-
-on:
-  push:
-    branches: [ "master" ]
-  pull_request:
-    # The branches below must be a subset of the branches above
-    branches: [ "master" ]
-  schedule:
-    - cron: '29 13 * * 4'
+on: [push, pull_request]
 
 jobs:
-  flawfinder:
-    name: Flawfinder
+  flawfinder_analysis:
     runs-on: ubuntu-latest
-    permissions:
-      actions: read
-      contents: read
-      security-events: write
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+    - uses: actions/checkout@v3
+      with:
+        fetch-depth: 0  # Fetch all history for all tags and branches
 
-      - name: flawfinder_scan
-        uses: david-a-wheeler/flawfinder@8e4a779ad59dbfaee5da586aa9210853b701959c
-        with:
-          arguments: '--sarif ./'
-          output: 'flawfinder_results.sarif'
+    - name: Install flawfinder
+      run: sudo apt-get install flawfinder
 
-      - name: Upload analysis results to GitHub Security tab
-        uses: github/codeql-action/upload-sarif@v2
-        with:
-          sarif_file: ${{github.workspace}}/flawfinder_results.sarif
+    - name: Run flawfinder and generate report
+      run: flawfinder --context . > flawfinder_report.txt
+
+    - name: Check if passing
+      run: |
+        if ! grep -Fq "No hits found" flawfinder_report.txt; then
+          echo "'No hits found' not in flawfinder_report.txt, failing pipeline."
+          exit 1
+        fi
+
+    - name: Upload flawfinder report
+      uses: actions/upload-artifact@v3
+      with:
+        name: flawfinder-report
+        path: flawfinder_report.txt
